### ISSUE TITLE
Duplicate where clauses

### ISSUE THREAD

**Issue by guzart** [holyketzer/activeadmin-ajax_filter#14]
Using:
* activeadmin 1.0.0.pre4
* activeadmin-ajax_filter 0.3.5

It seems that the [`collection`](https://github.com/holyketzer/activeadmin-ajax_filter/blob/master/lib/active_admin/ajax_filter.rb#L17) method already contains the ransack query from `params[:q]`.

My guess is that it's probably because ActiveAdmin uses the `q` param for applying ransack queries to `collection`.

**Comment by risinglf** [comment]
+1

**Comment by holyketzer** [comment]
Yes guys, you are right. I fixed that.
