### ISSUE TITLE
ActionView::Template::Error (undefined method `result' for nil:NilClass

### ISSUE THREAD

**Issue by railsfactory-palpandi** [holyketzer/activeadmin-ajax_filter#18]
ActionView::Template::Error (undefined method `result' for nil:NilClass):
    1: insert_tag renderer_for(:new)
  
app/admin/course.rb:43:in `block (5 levels) in <top (required)>'
app/admin/course.rb:35:in `block (4 levels) in <top (required)>'
app/admin/course.rb:33:in `block (3 levels) in <top (required)>'
app/admin/course.rb:24:in `block (2 levels) in <top (required)>'
  Rendering /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout
  Rendering /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (12.2ms)
  Rendering /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.8ms)
  Rendering /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/palpandi/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (37.0ms)

**Comment by holyketzer** [comment]
It's better to share version of gem which you use and source code what causes this error.

**Comment by railsfactory-palpandi** [comment]
Gem versions are 

rails 5.0.1,
activeadmin 1.0.0.pre5, and  
activeadmin-ajax_filter

**Comment by holyketzer** [comment]
I mean which version of `activeadmin-ajax_filter` do you exactly use. There was an issue and it fixed, make sure that you use latest version it is `0.3.7` now
