### ISSUE TITLE
Multi-select support

### ISSUE THREAD

**Issue by vraravam** [holyketzer/activeadmin-ajax_filter#20]
hi, In the [following commit](https://github.com/agilie/activeadmin-ajax_filter/commit/1ab3e7609df5f8319fb5a95e43ec13c81714513c), there's support for multi-select. Though the multi-select seems to be working in the filter field, when it gets posted to the server (for a filter that is configured with this gem), only the first value gets posted, thus returning filtered results only for the first selection. Please fix asap?

**Comment by vraravam** [comment]
@holyketzer - any reason for closing this issue? Was it fixed?

**Comment by holyketzer** [comment]
I'm doing it in my free time, and don't plan to support this feature ASAP. PRs are welcomed.

**Comment by vraravam** [comment]
in that case, would a "help wanted" badge be more useful - if anyone is interested in contributing a PR, they might be tempted to do so - but, if its closed, then there might not even be the knowledge that such a bug exists.
