### ISSUE TITLE
0.3.7 breaks rails 5 comatibility

### ISSUE THREAD

**Issue by phillc** [holyketzer/activeadmin-ajax_filter#21]
0.3.7 appears to have added a dependency on has_scope ~> 0.6.0, and that version of has scope has a dependency on actionpack < 5, >= 3.2.

**Comment by holyketzer** [comment]
Good point. 
Actually I didn't test it with Rails 5 support. If you can make PR it will be great or I will look into it later.

**Comment by vraravam** [comment]
@holyketzer : [has_scope](https://rubygems.org/gems/has_scope) now has a version that is compatible with rails < 5.2
