### ISSUE TITLE
Improvement on performance

### ISSUE THREAD

**Issue by mehmetaydogduu** [holyketzer/activeadmin-ajax_filter#44]
I integrated this gem but it worked slow than I expected. Large table, 3 fields. Then I created a controller with nativeson. It worked as 100 times faster than as_json.

Maybe you think use it as default json renderer.
https://gitlab.com/nativeson/nativeson

Another thing, it looks old than https://selectize.github.io/selectize.js/ site. Is it up to date?

**Comment by holyketzer** [comment]
It prematurely for me to conclude anything about performance, could you share your logs or performance profiling for these requests for default controller and with nativeson?

Selectize.js is up to date, there wasn't new releases for several years.

**Comment by holyketzer** [comment]
I used to use https://github.com/ohler55/oj with Rails, it gives maximum performance boost on JSON rendering among all possible libraries I tried to use couple of years ago. And it integrates smoothly to AMS so you shouldn't change any controller or serializer.

**Comment by fastengineer** [comment]
I tried ams and nativeson in this repo
https://github.com/fastengineer/test

I didn't see any change on performance. With ams, without ams, with oj, without oj, with nativeson the result nearly 30ms. In 10 k record and 3 search fields.

**Comment by holyketzer** [comment]
Great work! @fastengineer I appreciate your feedback 
I experimented with it  a little https://github.com/holyketzer/test/commit/16e9e18de79ce5756f81265afbd1574bd75022b1 and nativeson looks good

#test_movies_ns_filter 38 ms
#test_movies_oj_filter 42 ms - 10% slower
#test_movies_filter    48 ms - 26% slower

Especially for larger objects:

#test_people_ns_filter 37 ms
#test_people_oj_filter 43 ms - 16% slower
#test_people_filter    47 ms - 27% slower

but performance improvement isn't seemed so dramatic as in your example, so I'm still don't understand what exactly happened when you was able to improve performance in your case in 100x, and how it will work with Oj, maybe good enough.

I have couple of strong concerns about changing default Rails way of serialising stuff:

1. nativeson itself looks kind of raw and not popular solution, and they say in readme that it isn't complete replacement of other serializers
2. I don't want to be opinionated in such kind of small gem and decide behind somebody's back what is better way to serialize things in somebody's application

From another side nativeson is a very curious project and it definitely has its own area, a half I year ago I implemented something similar inside of one of my apps to fetch heavy JSON fields from DB in a way which avoiding parsing them into a hash and serializing back to JSON, so I definitely would try nativeson maybe it solves my problems more smoothly.

**Comment by fastengineer** [comment]
Hi @holyketzer, great work. I viewed your commit. It is good test. Yes, there isn't enough difference. I don't know what happened on 100x case. In clean project it is always returns similar results. I have another project that have 1 million products, I will try on it.
