### ISSUE TITLE
Semantic version issue

### ISSUE THREAD

**Issue by borisrorsvort** [holyketzer/activeadmin-ajax_filter#47]
Hi, don’t you think that bumping sprocket major version would deserve more than a patch (0.4.5)? https://github.com/holyketzer/activeadmin-ajax_filter/commit/38946a509a39737a9fe2c776dd8e08ef71a957d4#diff-e79a60dc6b85309ae70a6ea8261eaf95R233

It has been braking many builds since sprocket 4 requires a new manifest.json and dependabot auto upgrade patches...

**Comment by holyketzer** [comment]
Thank for reporting this, I'm not very experienced maintainer )

Looks like I need to release patch update with sprocket 3 major version.

**Comment by borisrorsvort** [comment]
@holyketzer Thanks! that would be great 👍

**Comment by holyketzer** [comment]
I pushed version `0.4.6` with `sprocket 3` and `rails 4`
Yanked `0.4.5`
and pushed `0.5.0` with all latest dependencies. 

@borisrorsvort sorry for this, thank you for your feedback 👍
