### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by knightq** [holyketzer/activeadmin-ajax_filter#56]
Hello again and thank you also for this gem, to begin with ❤️ .

As asked for `activeadmin-async_panel`, is there any chance to make it compatible with Rails 7?

Standing to [RailsBump report](https://railsbump.org/gems/activeadmin-async_panel), it is not.

Thank you 🙏

**Comment by holyketzer** [comment]
Sorry for the delay, the Rails 7 support released in https://rubygems.org/gems/activeadmin-ajax_filter/versions/0.7.0
