### ISSUE TITLE
No route matches [GET], strange behaviour

### ISSUE THREAD

**Issue by sutherland007** [holyketzer/activeadmin-ajax_filter#6]
With filter works fine,
but with inputs throws No route matches [GET]. but the filter works.
Using this as example:
```
# Relation-resource
ActiveAdmin.register User do
  include ActiveAdmin::AjaxFilter
  # ...
end

# As a form input
ActiveAdmin.register Invoice do
  form do |f|
    f.input :user, as: :ajax_select, data: { search_fields: [:name], static_ransack: { active_eq: true } }
    # ...
  end
end
```

I've noticed this: 
the URL filter is like:` /admin/users` (this works)
in the inputs the URL is like: `/admin/invoices/users `(this trows the error, search is working and all data it's OK)

my activeadmin version is 1.0.0 pre 2 
Rails 4.2.6
Ruby 2.2.0

**Comment by holyketzer** [comment]
It's because of very simple filter URL inference, search shouldn't work in that case. 
To fix it just setup `url` option:

```ruby
# As a form input
ActiveAdmin.register Invoice do
  form do |f|
    f.input :user, as: :ajax_select, data: { url: '/admin/users/filter', search_fields: [:name], static_ransack: { active_eq: true } }
    # ...
  end
end
```

**Comment by sutherland007** [comment]
@holyketzer  thanks a lot, it worked.
