### ISSUE TITLE
Error when using route helper methods in filter data url

### ISSUE THREAD

**Issue by guzart** [holyketzer/activeadmin-ajax_filter#9]
When I try to use a route helper method in the filter options it throws an error, I imagine it's because it's trying to call the helper method before ActiveAdmin registers the routes.

Example: Use `filter_admin_users_path` instead of a static string with the url

```ruby
ActiveAdmin.register Invoice do
  filter :user, as: :ajax_select, data: { 
    url: filter_admin_users_path, # '/admin/users/filter', 
    search_fields: [:email, :customer_uid], 
    limit: 7,
  }
  # ...
end
```

I imagine this could be solve by either using a lambda to defer the execution until runtime, or maybe by requiring the dependant module at the top of the ActiveAdmin registration file.

Right now it's not a stopper for me since the default of `"#{method.to_s.pluralize}/filter"` is working great.

PS: Thank your for sharing this amazing plugin!!

**Comment by holyketzer** [comment]
Hi @guzart, thank you for feedback.

Url helpers isn't available from filters level, trying to use lamdas to evaluate them also failed, there is a workaround for that with passing symbols and sending them to `routes.url_helpers`. See updated readme.

**Comment by guzart** [comment]
Excellent, thank you for taking the time to look into this.
